from shortGPT.gpt import gpt_utils
import json

def generate_title_description_dict(content):
    out = {"title": "", "description":""}
    chat, system = gpt_utils.load_local_yaml_prompt('prompt_templates/yt_title_description.yaml')
    chat = chat.replace("<<CONTENT>>", f"{content}")
    
    max_attempts = 3 
    attempts = 0
    
    while (out["title"] == "" or out["description"] == "") and attempts < max_attempts:
        attempts += 1
        
        try:
            result = gpt_utils.llm_completion(chat_prompt=chat, system=system, temp=1)
            response = json.loads(result)
            
            if "title" in response:
                out["title"] = response["title"]
            if "description" in response:
                out["description"] = response["description"]
                
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON response on attempt {attempts}: {e}")
            if attempts == max_attempts:
                # Fallback: usar parte do conteúdo como título e descrição
                content_preview = content[:500] if len(content) > 500 else content
                out["title"] = content[:60] if len(content) > 60 else content
                out["title"] = out["title"].replace('\n', ' ').strip()
                out["description"] = content_preview.replace('\n', ' ').strip()
                print("Using fallback title and description from content")
        except Exception as e:
            if attempts == max_attempts:
                # Se falhar completamente, lançar exceção com contexto
                raise Exception(f"Failed to generate YouTube metadata after {max_attempts} attempts: {e}")
    
    # Se ainda estiver vazio após todas tentativas, usar valores padrão
    if out["title"] == "":
        out["title"] = "Untitled Short Video"
        print("Warning: Using default title 'Untitled Short Video'")
    if out["description"] == "":
        out["description"] = "Generated by ShortGPT"
        print("Warning: Using default description 'Generated by ShortGPT'")
        
    return out['title'], out['description']
